spring:
    application:
        name: bookingManagement
    #profiles:
    #    active: local
    datasource:
        platform: postgres
        driver-class-name: org.postgresql.Driver
        #url: jdbc:postgresql://localhost:5432/bookingManagement
        url: jdbc:postgresql://dpg-ctqleol2ng1s73eato70-a.oregon-postgres.render.com:5432/bookingmanagement

        #username: postgres
        username: bookingmanagement_user
        #password: ENC(pnUnYQn0ld1tbfwiymh1zTts4a4311fn)
        password: dWfivWHkVdOtLfiamLAimikvWTPgsGGB
    hikari:
        connection-timeout: 20000
        maximum-pool-size: 5
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate.ddl-auto: update
        show-sql: true
jasypt:
    encryptor:
        algorithm: PBEWithMD5AndDES
        iv-generator-classname: org.jasypt.iv.NoIvGenerator
        password: h7A@L(U.81XL

cron:
    expression:
        insertFlow: 0 0 22 1 * ?
server:
    port: 8080
